# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  release:
    types: [ published ]


  # just for testing
  push:
    branches:
      - publish-on-jfrog

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Use JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1

      - name: Config Gradle
        run: jfrog rt gradle-config

      - name: Prepare for JFrog
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          jfrog rt gradle clean artifactoryPublish -b build.gradle --build-name codestyle-rulesets --build-number $NEW_VERSION

      - name: Publish on JFrog
        run:  |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          jfrog rt bp codestyle-rulesets $NEW_VERSION --url https://leebmann24.jfrog.io/artifactory/codestyle-rulesets/

#      - name: Publish artifact
#        env:
#          GITHUB_TOKEN: ${{ secrets.TOKEN }}
#          GITHUB_ACTOR: ${{ secrets.ACTOR }}
#        run: |
#          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
#          echo "New version: ${NEW_VERSION}"
#          echo "Github username: ${GITHUB_ACTOR}"
#          ./gradlew -Pversion=${NEW_VERSION} publish